# Generated by Django 3.2.16 on 2023-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='author',
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Cognome'),
        ),
    ]
