# Generated by Django 3.2.16 on 2023-01-06 11:52

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0002_auto_20230106_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='patient',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
