# Generated by Django 3.2.16 on 2023-01-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0003_auto_20230106_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmeasure',
            name='unit',
        ),
        migrations.AddField(
            model_name='measure',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_care.unit'),
        ),
    ]
