# Generated by Django 4.1.5 on 2023-01-06 12:58

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0004_auto_20230106_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='measure',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
