# Generated by Django 4.1.5 on 2023-01-31 18:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care', '0006_ingredient_alter_patientmeasure_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.FloatField(verbose_name='Quantità')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_care.ingredient')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
